### ISSUE TITLE
VSCodium on Ubuntu XFCE needs --privileged

### ISSUE THREAD

**Issue by davidlwillson** [danchitnis/container-xrdp#4]
Thanks for making this. You've saved me so many hours. Sending you a heads up on an issue I hit with my use-case. I don't fully understand why, but I thought you might want to know.

When I start the ubuntu-xfce and install VSCodium like this:

```bash
wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg     | gpg --dearmor     | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.com/debs vscodium main'     | sudo tee /etc/apt/sources.list.d/vscodium.list
sudo apt update && sudo apt install codium
```

VSCodium(codium) never starts.

Use `codium --verbose` to show the error.

```
$ codium --verbose
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
```

I found the answer here: https://github.com/jessfraz/dockerfiles/issues/350. Add `--privileged` to the Docker command. So:

```bash
docker run --privileged -it -p 33890:3389 danchitnis/xrdp:ubuntu-xfce $USERNAME $PASSWORD $SUDOBOOL
```
Works.

Again, thanks for creating this project. It's a huge help to me as I try to get consistent environments for learners.

**Comment by danchitnis** [comment]
Happy that it did help you. The issue is related to chrome's engine and its sandbox concept. There are some solutions [here](https://github.com/Zenika/alpine-chrome). Make sure that you are aware of the security risks when running docker in `--privileged` mode.
