### ISSUE TITLE
Rebuild fedora images to upgrade to 37

### ISSUE THREAD

**Issue by voorth** [danchitnis/container-xrdp#5]

**Comment by danchitnis** [comment]
Updated the images, but I am afraid the *latest* Fedora is still 36.

**Comment by voorth** [comment]
OK - I need 37, because that supports the most recent version of a package I want to install. How about adding an ARG instruction above the FROM ? That way you can set the default version to "latest: but still build images based on other tags. I can provide a pull request if you like.

**Comment by danchitnis** [comment]
I suggest forking and modifying the top line to `FROM fedora:37`. The reason I don't want to include an ARG is that xrdp is not compatible will all versions of Linux. These have to be tested individually to make sure it actually works before pushing to the Docker Hub. It would be a hassle to do this manually unless there is an automated way to keep up with the updates. 

Can the ARG have a default value? So if the user doesn't include it falls back on `:latest`?

**Comment by voorth** [comment]
> Can the ARG have a default value? So if the user doesn't include it falls back on :latest?

It can indeed, just add the following line before the FROM : 
```
ARG TAG=latest
FROM fedora:$TAG

```
you can now override this with : 
`docker build --build-arg TAG=37 ...`

**Comment by danchitnis** [comment]
Okay, feel free to do a pull request. Thanks.

**Comment by voorth** [comment]
FYI: fedora:latest has just been updated to 37.
