### ISSUE TITLE
ubuntu latest showing blank screen 

### ISSUE THREAD

**Issue by vkovelkar** [danchitnis/container-xrdp#6]
I updated just ubuntu latest image and run the docker command/ it showing blank screen while longing into  the remote desktop

**Comment by vkovelkar** [comment]
while building  image in local .. i am getting below error.

W: Download is performed unsandboxed as root as file 'pulseaudio_15.99.1+dfsg1-1ubuntu2.dsc' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
Fetched 1540 kB in 0s (4070 kB/s)
Removing intermediate container 0546ed47407d
 ---> fab7a13620e7
Step 9/18 : RUN cd /pulseaudio-$(pulseaudio --version | awk '{print $2}')     && ./configure
 ---> Running in a9ac73ee988c
/bin/sh: 1: cd: can't cd to /pulseaudio-15.99.1
The command '/bin/sh -c cd /pulseaudio-$(pulseaudio --version | awk '{print $2}')     && ./configure' returned a non-zero code: 2

**Comment by danchitnis** [comment]
@vkovelkar I just built and tested ubuntu-xfce with no problem. What are the commands that you are using to build the image?

**Comment by vkovelkar** [comment]
@danchitnis  I download whole master branch and I try to build the image but am getting above error.
command :   " docker build  -t ubuntu:xdp ."

**Comment by danchitnis** [comment]
This is not the correct command. Are you following [this](https://github.com/danchitnis/container-xrdp/blob/master/build.md)? It is best to build it in Linux. If you still have errors during the build, then you have to upload the docker build logs here. Another option is to pull the image, and then update it inside the virtual environment like normal ubuntu.

**Comment by toastie89** [comment]
I see the same issue with the Ubuntu version on dockerhub. After login there is a black screen and mouse pointer, but nothing else.

**Comment by danchitnis** [comment]
@toastie89 can you run fedora or amazon? or is it only ubuntu?

**Comment by toastie89** [comment]
Same with the Fedora image. On the same host with the same RDP client the image from [danielguerra69/ubuntu-xrdp](https://github.com/danielguerra69/ubuntu-xrdp/) runs fine. I'll try tomorrow with another host.

**Comment by danchitnis** [comment]
Not sure what is going on. On my machine with the new Docker doesn't work at all. On my other machine with old Docker runs but has your blank screen problem which generally means a bug has appeared among xrdp and its related packages. I should have kept the old images. I will update whenever I get it working again.

**Comment by danchitnis** [comment]
issue reported [here](https://github.com/docker/for-win/issues/13216) and [here](https://github.com/docker/for-win/issues/13229) with Docker v4.16.3. You need to change the RDP port on Windows using the instruction here until the bug is fixed. Other than your Docker or WSL version might be too old. The containers run without problems other than the mentioned bug.

**Comment by toastie89** [comment]
I've verified with a more recent docker host and the issue doesn't exist there.
